name: Test Wall Post

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install mwclient requests
      - name: Run test
        env:
          WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
          WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
          TEST_USER: "Swit4er"
        run: python src/scripts/bots/test_post.py
